
### get courses
GET http://localhost:3000/courses

### create course
POST http://localhost:3000/courses HTTP/1.1
Content-Type: application/json

{
  "name": "mecanica"
}

### update course
PUT http://localhost:3000/courses/1 HTTP/1.1
Content-Type: application/json

{
  "name": "museo"
}

### add student to course
PUT http://localhost:3000/courses/5/addStudent/2 HTTP/1.1
Content-Type: application/json

##{
#  "courseId": "5",
#  "studentId": "1"
##}
