## get teachers
GET http://localhost:3000/teachers

### create teacher
POST http://localhost:3000/teachers HTTP/1.1
Content-Type: application/json

{
  "firstName": "miguel",
  "lastName": "alvarez",
  "image_url": ""
}

### update teacher
PUT http://localhost:3000/teachers/1 HTTP/1.1
Content-Type: application/json

{
  "firstName": "miguel",
  "lastName": "lopez",
  "image_url": "d"
}